services:
  postgres:
    build:
      target: postgres
      context: .
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=main
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready
        - --quiet
        - --username=postgres
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data/
  pg-admin:
    build:
      context: .
      dockerfile: Dockerfile
      target: pg-admin
    ports:
      - 15433:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=default@mail.com
      - PGADMIN_DEFAULT_PASSWORD=password
volumes:
  pg-data: {}
